name: Auth CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/auth/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/auth/**'
  workflow_dispatch:

jobs:
  ci-auth:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/auth
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements-dev.txt
      - name: Lint
        run: |
          flake8 .

      - name: Format check with Black
        run: |
          black --check --diff .

      - name: Run tests with pytest
        run: |
          pytest tests/ -v --tb=short --cov=. --cov-report=term-missing
        env:
          PYTHONPATH: .
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/dianovi/auth:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

    # cd auth
    # Get K8s Credentials
    # Apply K8s/Helm Chart
