name: Auth CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/auth/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/auth/**'

jobs:
  auth:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/auth
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Lint
        run: |
          pip install flake8
          flake8 .
      - name: Build Docker image
        run: docker build -t dianovi/auth:latest .
